### ISSUE TITLE
Implement CardRepostory to OctokitRepository

### ISSUE THREAD

**Issue by HiromiShikata** [HiromiShikata/github-issue-working-time-reporter#7]
## ref
- [CardRepository](https://github.com/HiromiShikata/github-issue-working-time-reporter/blob/main/src/domain/usecases/repositories/CardRepository.ts) 
- [OctoKitCardRepository](https://github.com/HiromiShikata/github-issue-working-time-reporter/blob/main/src/adapter/repositories/OctkitCardRepository.ts)
- env variable name of github access token is GH_TOKEN

## requirement
- use v4 api (graphql api) of github
- unit testing is required

**Comment by webmobileai** [comment]
I have your job on upwork.
Gmail : coindevmentor9211@gmail.com
Please let me know task.
Thanks

**Comment by ghost** [comment]
I have commented on upwork
gentledeveloper48@gmail.com

Please let me know your task in more detail.
thanks
